:concept-flow: 🌊 Flow of information

= {concept-flow}

[pikchr, width=75%]
....
movewid = 0.5in

right
A: box wid 0.4in ht 1in
B: box wid 0.5in ht 0.8in with .nw at movewid*0.8 ne of last.ne
C: box wid 0.6in ht 0.5in with .w at movewid*0.8 se of last.e

spline -> from movewid sw of A \
  then to A then to B then to C
....

[.notes]
--
First, I want to introduce this concept.
I don't know if there's a formal name for this, but I've been calling it
flow of information --
the path that information takes to go through your application.

Its shape may change as it passes through,
but the information represented is similar if not the same.
--

[%auto-animate]
== {concept-flow}

[pikchr, width=800px]
....
linewid = 0.2in
linerad = 0.1in

define data { box $1 mono color 0x0A9396 rad 0.1in fit  }
define func { box $1 mono color 0xCA6702 fit }

CLI: [
  data("[]string")
  arrow
  func("flag.Parse()")
  line
  data("Options")
  arrow
  text "..."
]
....

[%step]
[pikchr, width=900px]
....
linewid = 0.2in
linerad = 0.1in

define data { box $1 mono color 0x0A9396 rad 0.1in fit  }
define func { box $1 mono color 0xCA6702 fit }
HTTP: [
  Request: data("*http.Request")

  JSON: func("json.Unmarshal") with .sw at 0.2in ne of Request.ne
  line
  data("GetUserRequest")

  Headers: func("extractHeaders") with .nw at 0.2in se of Request.se
  line
  data("AuthToken") same as GetUserRequest

  arrow from Request.n up until even with JSON \
    then right to JSON chop
  arrow from Request.s down until even with Headers \
    then right to Headers chop

  func("Handle") at 0.2in e of (0.5 of the way between GetUserRequest.e and AuthToken.e)
  arrow chop from GetUserRequest right until even with Handle then to Handle
  arrow chop from AuthToken right until even with Handle then to Handle
]
....

[.medium%step]
Flow in one direction [.step]#without backtracking#

[.notes]
--
For example, when you parse command line arguments,
the slice of strings gets transformed to, say, an `Options` struct.
It's roughly the same information,
but with unimportant bits chipped away.

Similarly, (*step*)
when you parse an HTTP request --
maybe JSON decoding the body,
and extracting some information from headers --
it's again roughly the same information minus the unimportant bits.

In both cases, (*step*) information flows in one direction.
We don't touch the original list of command line arguments,
or the original request body again.
That is, (*step*) there's no backtracking.
--

[%auto-animate]
== {concept-flow}

Flow in one direction without backtracking

[%step]
[pikchr, width=80%]
....
linewid = 0.2in
lineht = 0.2in
linerad = 0.1in
movewid = 0.2in

define data { box $1 mono color 0x0A9396 rad 0.1in fit  }
define func { box $1 mono color 0xCA6702 fit }

A: [
  right
  String: data("string")
  arrow
  SSH: func("isSSH")
  move
  Download: func("sshDownload")
  move
  URLParse: func("url.Parse")
  line
  data("url.URL")
  arrow
  text "..."

  define fromString {
    arrow chop from String up $2 then right until even with $1 then to $1
  }
  fromString(Download, 0.3in)
  fromString(URLParse, 0.35in)

  define toString {
    arrow dashed chop from $1 down $2 then left until even with String then to String
  }
  toString(SSH, 0.3in)
  toString(Download, 0.4in)
]

text "Bad" at movewid west of A.w
....

[%step]
[pikchr, width=80%]
....
linewid = 0.2in
lineht = 0.2in
linerad = 0.1in
movewid = 0.2in

define data { box $1 mono color 0x0A9396 rad 0.1in fit  }
define func { box $1 mono color 0xCA6702 fit }

A: [
  right
  String: data("string")
  arrow
  URLParse: func("url.Parse")
  line
  URL: data("url.URL")
  arrow

  SSH: func("isSSH")
  arrow
  Download: func("sshDownload")

  line
  text "..."
]

text "Good" at movewid west of A.w
....

[.notes]
--
Apply the same principle to chaotic data --
strings and other primitives that hold structure.
Interpret their structure once, and never go back to it.

Think back to the section about parsing.
We had a function that matched the scheme -- HTTP or SSH --
and downloaded a file.

(*step*) Even narrowing to just the SSH flow,
we backtrack to the string and re-interpret its meaning.
Every function that touches the chaotic string
has to interpret the structure of the string.
It cannot *assume* that the string is a URL, it has to check.

(*step*) Compare that with parsing the string early.
Information flows forward and nobody touches the chaotic form again.
--

== {concept-flow}

[%step]
--
[pikchr, width=50%]
....
linewid = 0.2in
lineht = 0.2in
linerad = 0.1in
movewid = 0.3in


A: box wid 0.5in ht 0.8in
move
B: box same

spline -> from 0.1in s of A.n to 0.1in s of B.n \
  then to 0.2in s of A.n to 0.2in s of B.n \
  then to 0.4in s of A.n to 0.6in s of B.n
....

Zigzagging flow indicates a leak
--

[.notes]
--
The consistent flow of information is important at the micro level
as well as the macro level.
Consider how information flows between functions or packages?
Is it flowing in one direction consistently or zigzagging (*step*)?

If it's zigzagging,
there's either a leak of complexity,
or a very tight coupling between these objects.
--
