:concept-scope: 🔍 Scope

[.columns]
= {concept-scope}

[.column%step]
--
*Application scope*

[.medium]
Does not change between requests

* Command line arguments
* Environment variables
--

[.column%step]
--
*Request scope*

[.medium]
Changes for each request

* HTTP request
* ???
--

[.notes]
--
Next, I want to talk about the concept of scope.

Again, I'm just making up this term --
if you know a more formal name for it, please come find me afterwards.

By scope, I'm thinking not of lexical scope,
but what lifetime a value is bound to.

Consider two kinds of scope:

* (*step*) Application scope is for values that don't change between calls.
  Your `os.Args`, the process' environment variables, etc.
  Yes, we can mutate them, but practically,
  they're constant as far as any business logic in concerned.
* (*step*) And request scope. Things that change per call.
  Obviously, this includes your HTTP request.
  But what else? Well, everything, really. Depends on how you look at it.
--

== {concept-scope}

Scope is relative

[%step]
[pikchr, height=500px]
....
// (0, 0) is the start of the arrow
A: arrow <-> right 2.5in
text "application scope" "(rarely changes)" with .e at last arrow.w
text "request scope" "(changes often)" with .w at last arrow.e

BigScope1: dot invis at (0, 0.75in)
BigScope2: dot invis at (0, -0.75in)

S1: arrow <-> thin color gray from BigScope1 to (A.e.x+0.1in, 0.3in)
S2: arrow <-> thin color gray from BigScope2 to (A.e.x+0.1in, -0.3in)
line thin color gray from 0.2in east of BigScope1 go left 0.1in
line thin color gray from 0.2in east of BigScope2 go left 0.1in
line thin dotted color gray from last line to 2nd last line
line invis "scope size" below aligned color gray from 2nd last line to 0.5 way between 2nd last line and 3rd last line

dot at (0.6in, 0)
line invis from last dot go 0.15in heading 135 "os.Args" mono aligned ljust

line thin from (last dot.x-0.15in, 0.1in) down 0.2in
text "flag.Parse" mono ljust with .s at last.n

dot at (A.e.x-0.4in, 0)
line invis from last dot go 0.15in heading 135 "http.Request" mono aligned ljust

line thin from (last dot.x-0.15in, 0.1in) down 0.2in
text "http.Handler" mono with .s at last.n
....

[.notes]
--
Whether something is request scope or application scope depends
on your point of view.

Command line arguments are application scope, yes.
But from the point of view of a command line argument parser,
they're request scope.

So instead of a binary definition, think of scope as a gradient.
(*step*)

* As we go from left to right, the scope of each value gets smaller
  because it changes more often.
* So things on the left are application scoped to those on the right,
  and things on the right are request scoped to those on the left.

For example, `flag.Parse` views this from further left of `os.Args`,
so from its point of view, `os.Args` is request scope.
On the other hand, `http.Handler` views it from further right,
so from its point of view, `os.Args` is application scope.

Thinking about the relative scope of different values
can be really helpful in writing code.
--

[.columns.wrap]
== {concept-scope}

[cols="1h,2a,^2a"]
|====

| Structs
| [%hardbreaks.medium]
Large scope: fields
Small scope: parameters
| [pikchr, width="80%"]
....
// (0, 0) is the start of the arrow
A: arrow <-> right 1.5in

dot at (0.3in, 0)
line invis from last dot go 0.15in heading 135 "Logger" mono aligned ljust

line from (last dot.x+0.4in, 0.1in) down 0.2in
text "RequestHandler" mono with .s at last.n

dot at (A.e-0.3in, 0)
line invis from last dot go 0.15in heading 135 "Request" mono aligned ljust
....

| Interfaces
| [%hardbreaks.medium]
Request-scoped methods
on the interface
| [source,go]
----
type Store interface {
  Get(string) (string, error)
  Set(k, v string) error
}
----

| Parameters
| [.medium]
Sort by scope (big to small)
| [source,go]
----
func GetUser(
  org, username string,
) *User
----

|====

[.notes]
--
For example,

* Use it to help you decide which inputs become struct fields,
  and which become method parameters.
  Things with a scope larger than a single struct value
  can become fields of the struct.
  Others can become parameters of methods on the struct.
* Similarly, use it to design interfaces.
  Only request-scoped methods go on the interface.
  Think back to the `RedisStore` example --
  Get and Set are request scoped, Close is not.
* Finally, you can even use the concept of scope
  to help you decide on parameter ordering if you're unsure.
  Just sort parameters by scope: larger to smaller.
  Things that change less often, go on the left,
  things that change more often, on the right.
--
