= What makes a package future-proof?

[quote]
The ability to evolve in functionality +
without disrupting the code base

[.notes]
--
What do I mean when I say future-proof package?

For this talk, I'm making up this definition.

A package is future-proof
if it has the ability to evolve in functionality
without disrupting rest of code base.
--

== Disruption

[quote]
Being forced to modify code +
as a result of an unrelated change

[.notes]
--
What do I mean by disruption here?

Being forced to modify code that previously worked,
and is otherwise unrelated,
as a result of a change elsewhere in the codebase.

Disruptions are bad.

* They reduce your velocity:
  you're left doing unnecessary mechanical work
* They reduce your team's velocity:
  they have to make their own disruptive changes,
  they have to review these mechanical changes,
  and they have to deal with the resulting merge conflicts.

All in all, they're inconvenient.
--

== What causes disruption?

[%step]
[.step.fade-out]#Changes to packages with# +
a design that *leaks complexity*

[.notes]
--
Why does this happen?
What prevents us from evolving packages without disruptions?

This is my main thesis of my talk today:
(*next*)
code disruptions are caused by changes to packages
with a design that leaks complexity.

(*next*)
A design that leaks complexity.

Let me expand that.
--

== On complexity

[pikchr, height=250px]
....
X: [
A: box invis wid 0.7in ht 1in

line rad 0.02in color 0x94D2BD \
  from A.nw go 0.15in s \
  then 0.1in w then 0.1in s then 0.1in e then 0.1in s \
  then 0.1in w then 0.1in s then 0.1in e then 0.1in s \
  then 0.1in w then 0.1in s then 0.1in e then 0.1in s \
  then 0.1in w then 0.1in s then 0.1in e then 0.1in s \
  then to A.sw to A.se \
  then 0.3in n \
  then 0.3in w then 0.3in n then 0.3in e \
  then to A.ne to A.nw
]

Y: [
A: box invis wid 0.7in ht 1in

line rad 0.02in color 0xEE9B00 \
  from A.nw go 0.15in s \
  then 0.1in w then 0.1in s then 0.1in e then 0.1in s \
  then 0.1in w then 0.1in s then 0.1in e then 0.1in s \
  then 0.1in w then 0.1in s then 0.1in e then 0.1in s \
  then 0.1in w then 0.1in s then 0.1in e then 0.1in s \
  then to A.sw to A.se \
  then 0.2in n \
  then 0.2in w then 0.2in n then 0.2in e then 0.1in n \
  then 0.1in w then 0.1in n then 0.1in e then 0.1in n \
  then 0.1in w then 0.1in n then 0.1in e then 0.1in n \
  then to A.ne to A.nw
] with ne at 0.7in w of last.nw

text "Hidden Complexity" big with s at X.n
text "Leaking Complexity" big with s at Y.n
....

* Complexity is inevitable
* Good design hides complexity
* Complexity leaks cause fragility
* Fragility causes disruption

[.notes]
--
The existence of complexity is unavoidable.
Non-trivial systems deal with it at _some_ layer
so it has to exist somewhere.

The purpose of good design is to hide this complexity.

When it fails to do so, you get a fragile system,
and that fragility causes the disruptions we're talking about.
--
