:concept-area-depth: 📦 Surface area and depth

[.columns]
= Surface area

[.column.is-one-third]
--
--

[.column.text-left]
--
[pikchr,height=300px]
....
box "package" fit ht 0.5in
line thick color 0xEE9B00 "surface area" above from 0.05in above last.nw right until even with last.e
....
--

[.notes]
--
Surface area refers to the things exported from a package.
The part of a package that other packages can "touch".

Every exported function, type, and method is an entry point to the package,
so it adds to the surface area.

Surface area does not correspond to how much functionality the package offers.
That's a job for depth.
--

[.columns]
== {concept-area-depth}

[.column.is-one-third]
--
--

[.column.text-left]
--
[pikchr,height=300px]
....
box "package" fit ht 0.5in
line thick color 0xEE9B00 "surface area" above from 0.05in above last.nw right until even with last.e

line thick color 0x0A9396 " depth" ljust from 0.05in east of last box.ne down until even with last box.se
....
--

[.notes]
--
Depth refers to how much work is done by exported components of a package.
The deeper a package, the more work is being done.

In combination, these represent the total functionality offered by the package.
--

== {concept-area-depth}

[pikchr, height=400px]
....
define areaAndDepth {
  line color 0xEE9B00 from $1.nw to $1.ne
  line color 0x0A9396 from $1.ne to $1.se
}

box "strings" fit width 2in thin
areaAndDepth(last box)
text "Shallow and wide" with e at 0.3in west of last box.w

box "archive/tar" fit ht 1in thin with nw at 0.1in south of last box.sw
areaAndDepth(last box)
text "Narrow and deep" with e at 0.3in west of last box.w
....

[.notes]
--
Consider two ends of the area-depth ratio:

* On one end, packages can be shallow and wide.
  These will consist of lots of small helper functions.
  Lots of little entry points each doing small amounts of work.
* On the other end, they can be narrow and deep.
  Few entry points, hiding away a large amount of work.
--

[.columns.wrap]
== {concept-area-depth}

[.column.is-half]
--
Wide and shallow packages

* Frequent entry and exit
* May cause zigzagging
--

[.column.is-half]
--
Narrow and deep packages

* Very few entry points
* Upfront design work
--

[.column.is-full%step]
--
Business packages should be narrow and deep
--

[.notes]
--
Just by virtue of their design,
wide and shallow packages encourage frequent entry and exit.
This can cause zigzagging if you're not careful.

While narrow and deep packages don't --
at the cost of some upfront design work.

So when it comes to business logic,
(*step*) business packages should aim to be
narrow in surface area and deep in functionality.
--

[.columns]
== {concept-area-depth}

[.medium.column]
--
[.text-align]
Might be wide and shallow if +
there are top-level functions that

* Do RPC and IO
* Access global state
* Have shared arguments
* Are interrelated
* [.step]#Are in 'util'#
--

[.column]
--
[pikchr]
....
Shallow: [
box "userutil" mono ht 0.3in wid 2in

// func{Above,Below}(distance from w, name)
define funcBelow {
  dot at $1 east of 1st box.w
  line thin from last dot down 1st box.ht
  text $2 mono below at last line.s
}
define funcAbove {
  dot at $1 east of 1st box.w
  line thin from last dot up 1st box.ht
  text $2 mono above at last line.n
}

funcBelow(0.3in, "GetUserList")
funcAbove(0.5in, "FilterUsers")
funcBelow(1.7in, "UserIsAdmin")
]

Deep: [
linewid = 0.3in
right
text "ListAdmins" mono
arrow
box "UserService" mono fit ht 0.75in
arrow
text "[]*User" mono
] with .n at 0.5in south of Shallow.s

text "Wide and shallow" big bold at 0.2in w of Shallow.nw+(0,0.05in)
text "Deep and narrow" big bold at (last.x, Deep.n.y+0.1in)
....
--

[.notes]
--
You probably have a business package that is wide and shallow
if it matches the following general pattern.

* It has a bunch of top-level exported functions
  implementing complex business logic --
  you know, making HTTP requests, writing to disk, etc.
* Some of these functions probably access global state at some point,
  or maybe just have a tonne of parameters.
* They are heavily interrelated; output of one function is input to another.
* (*step*) They might even sit in a file or package named util.

To prevent something like this,
we have to find a named abstraction for the purpose of those functions.
What are they all for?
Give that a name and a single entry point,
and you might get a narrower, deeper abstraction out of that.
--
