= Zooming out

[.notes]
--
Zooming out.

I've been talking about very specific code samples.
I'm going to zoom out a bit and talk about applications as a whole.
--

include::concept-flow.adoc[]
include::concept-scope.adoc[]
include::concept-area-depth.adoc[]

= Finding the abstraction

[.notes]
--
Okay so, the concepts I just talked about:
flow, scope, surface area, and depth.
They can help you find the right abstraction to hide complexity.
Let me demonstrate with a couple examples.
--

// include::fix-long-funcs.adoc[]
include::find-conds.adoc[]
include::find-curry.adoc[]

[.columns.wrap]
= Writing the abstraction

[.column.is-half.text-left%step]
--
*Start on the outside*

[.medium]
Design => Document => Implement
--

[.column.is-half.text-right%step]
--
*Name things clearly*

[.medium]
Be consistent, re-use terms, +
no kitchen sinks
--

[.column.is-half%step]
--
[.text-left]
*Don't leak internals*
--

[.column.is-half.text-right%step]
--
*Don't add features, +
integrate*
--

[.notes]
--
Some tips for writing the abstraction once you've found it

* (*step*) Start on the outside:
  Decide the contract first, document it, and *then* implement it.
* (*step*) Name things clearly:
** Pick a consistent naming scheme,
   and re-use terms for similar concepts of introducing new ones.
** For example, if you have UserDetails already,
   don't introduce PostData -- call it PostDetails.
   Each new term is a new thing a user has to incorporate
   into their mental model of the package.
** Oh and don't create kitchen sink packages like 'util'.
   That's what causes shallow and wide business code.
// * (*step*) Use the tools discussed previously --
//   parameter and result objects, functional options,
//   accept interfaces, return structs --
//   to plan for expansion of the abstractoin.
* (*step*) Don't leak the implementation.
  Define domain-specific data types,
  and expose those from your abstraction.
* (*step*) Lastly, don't just add a new feature.
  Features don't exist in isolation.
  Consider how the new feature interacts with other features,
  and integrate it.
  Don't just add an `OmitSlash` boolean, add a `LinkStyle` property.
--
