[%auto-animate%auto-animate-restart.columns]
= Result objects

[.column.medium, data=id=list]
--
Put the outputs into a struct
--


[.column.medium]
[source%linenums,go,data-id=list]
----
type ListPageResult struct {
  Items      []*Item
  ContinueAt ItemID
}

func ListPage(from *ItemID) (*ListPageResult, error) {
  /* ... */
}
----

[.notes]
--
Result objects are the same idea, but for return values.
If you expect to produce more outputs in the future,
put them in a struct and return that instead.

You can produce new outputs without disrupting callers.
--

[%auto-animate.columns]
== Result objects

[.column, data=id=list]
--
Put the outputs into a struct

[%step.medium]
* Use for >2 returns +
  [.step.medium]#not counting `error`#
* Obvious field names
--

[.column.medium]
[source%linenums,go,data-id=list]
----
type ListPageResult struct {
  Items      []*Item
  ContinueAt ItemID
  Remaining  int
}

func ListPage(from *ItemID) (*ListPageResult, error) {
  /* ... */
}
----

[.notes]
--
* (*step*) Result objects are a good idea
  for functions that want to return more than two outputs
  (*step*) not counting the error.
* (*step*) Use the field names effectively.
  In result objects, the field names are a great lever
  to control how code that consumes this looks.
  Code that consumes the result object becomes more readable
  just because they *have* to use the name you chose
  for the field.
--
