[%auto-animate%auto-animate-restart.columns]
= Functional options

[.column.is-half]
--
🙂::
[none]
* Flexible
* Customizable
🙁::
[none]
* Complex
--

[.column.is-half]
--
[source%linenums,go,data-id=New,highlight="1-|1|3|4-7"]
----
type Option func(*clientOptions)

func New(opts ...Option) *Client {
  var options clientOptions
  for _, opt := range opts {
    opt(&options)
  }
  /* ... */
}
----

[source%linenums.medium,go,data-id=options,highlight="1-|2|5,7"]
----
type clientOptions struct {
  logger *slog.Logger
}

func WithLogger(l *slog.Logger) Option {
  return func(o *clientOptions) {
    o.logger = l
  }
}
----
--

[.notes]
--
Finally, there's Functional Options.
This is a pretty popular pattern that provides
a flexible, super-customizable DSL
to pass parameters and extract results from a function.

It's also a bit messy and complex.

The general shape of functional options is:

* (*step*) There's an Option type that manipulates a data structure -- usually private.
* (*step*) The function this is for accepts a variable number of these options.
  (*step*) It instantiates the private data structure and applies the options to it.
* (*step*) For each option, you add a field to the private data structure,
  (*step*) and a function to build that option.
--

[%auto-animate.columns]
= Functional options

[.column.is-half]
--
[source%linenums,go,data-id=New]
----

type Option func(*clientOptions)

func New(opts ...Option) *Client {
  var options clientOptions
  for _, opt := range opts {
    opt(&options)
  }
  /* ... */
}
----

[pikchr, height=200px, data-id=diag]
....
movewid = 0.3in
boxrad = 0.05in
linerad = 0.1in
lineht = 0.3in

right
box "WithLogger" mono fit wid 0.9in
move
box "WithHTTPClient" mono same
move
Dots: box "..." mono same

New: box "New(...Option)" mono fit wid 0.9in with n at movewid south of WithHTTPClient.s
Mid: dot invis at 1/2 way between last box.n and WithHTTPClient.s

arrow chop from WithLogger go down until even with Mid then right to Mid then to last box
arrow chop from WithHTTPClient to last box
arrow chop from Dots go down until even with Mid then left to Mid then to last box

move to New.s
Options: box "clientOptions" mono same with n at movewid s of New.s
arrow chop dotted from 0.1in west of New.s down until even with last.n
arrow <- chop dotted from 0.1in east of New.s down until even with last box.n

arrow chop dotted from Options.w left until even with 0.1in west of WithLogger \
  then up until even with WithLogger.s
arrow chop dotted from WithLogger to WithHTTPClient
arrow chop dotted from WithHTTPClient to Dots
arrow chop dotted from 0.1in east of Dots.s down until even with Options then to Options
....
--

[.column.is-half]
--
[source%linenums.medium,go,data-id=options]
----
type clientOptions struct {
  logger *slog.Logger
  /* ... */
  httpClient *http.Client
}

func WithLogger(l *slog.Logger) Option {
  return func(o *clientOptions) {
    o.logger = l
  }
}

func WithHTTPClient(c *http.Client) Option {
  return func(o *clientOptions) {
    o.httpClient = c
  }
}
----
--

[.notes]
--
There's room for unlimited growth here at the cost of complexity.

That diagram demonstrates roughly the relationships
between the entities here.

* WithLogger, WithHTTPClient, and other options feed into New.
* New constructs clientOptions,
  and feeds that back into WithLogger and friends.
* Each option modifies the clientOptions struct,
  leaving us with the consumable version at the end.
--

[%auto-animate.columns.wrap]
= Functional options

[.column.is-one-third]
[pikchr, height=200px, data-id=diag]
....
movewid = 0.3in
boxrad = 0.05in
linerad = 0.1in
lineht = 0.3in

right
box "WithLogger" mono fit wid 0.9in
move
box "WithHTTPClient" mono same
move
Dots: box "..." mono same

New: box "New(...Option)" mono fit wid 0.9in with n at movewid south of WithHTTPClient.s
Mid: dot invis at 1/2 way between last box.n and WithHTTPClient.s

arrow chop from WithLogger go down until even with Mid then right to Mid then to last box
arrow chop from WithHTTPClient to last box
arrow chop from Dots go down until even with Mid then left to Mid then to last box

move to New.s
Options: box "clientOptions" mono same with n at movewid s of New.s
arrow chop dotted from 0.1in west of New.s down until even with last.n
arrow <- chop dotted from 0.1in east of New.s down until even with last box.n

arrow chop dotted from Options.w left until even with 0.1in west of WithLogger \
  then up until even with WithLogger.s
arrow chop dotted from WithLogger to WithHTTPClient
arrow chop dotted from WithHTTPClient to Dots
arrow chop dotted from 0.1in east of Dots.s down until even with Options then to Options
....

[%step.column.is-one-third]
--
🙁

[.medium]
* High boilerplate
* Harder to test
* Corner cases
--

[%step.column.is-one-third]
--
🙂

[.medium]
* Several options
* Few required inputs +
  [.step.medium]#*not* as options#
* Composability
--

[%step.column.is-full]
--
Don't use by default. Prefer parameter objects.
--

[.notes]
--
I could have a longer discussion about functional options,
but for lack of time, I'll summarize it: (*step*)

* Functional options require a high amount of boilerplate
* It's harder for consumers to test their usage of APIs
  that use functional options.
  For example, is my mock matching against the options or their effect?
** Remember that these objects are just function references.
   You cannot inspect or compare them.
* Options come with corner cases that people don't often think about.
  What happens if I provide the logger option twice?
  Is that a replacement or a merge?
  If it's a merge, how do I un-provide a logger that someone else provided
  to the options slice?

On the good side (*step*), functional options are probably a good fit if
you intend to have *many* many options and very few required inputs.
(*step*)
Required inputs must not be options -- the names should make that obvious.

(*step*)
Again, functional options are a great tool when they fit,
but that's not the default.
Don't reach for them by default. Prefer parameter objects.
--

// [%auto-animate.columns]
// == Functional options
//
// [.column.is-half]
// --
// [source%linenums,go,data-id=Option]
// ----
// type Option func(*clientOptions)
// ----
// --
//
// [.column.is-half]
// --
// [source%linenums.medium,go,data-id=options]
// ----
// func WithLogger(l *slog.Logger) Option {
//   return func(o *clientOptions) {
//     o.logger = l
//   }
// }
// ----
// --
//
// [.notes]
// --
// The type's shape is also up to you.
// In the example above, I used a `func`,
// but there's nothing stopping it from being an interface instead.
// --
//
// [%auto-animate.columns]
// == Functional options
//
// [.column.is-half]
// --
// [source%linenums,go,data-id=Option]
// ----
// type Option interface {
//   apply(*clientOptions)
// }
// ----
//
// [source%linenums.medium,go,step=1]
// ----
// func (o *loggerOption) String() string {
//   return fmt.Sprintf("WithLogger(%v)", o.l)
// }
// ----
// --
//
// [.column.is-half]
// --
// [source%linenums.medium,go,data-id=options]
// ----
// type loggerOption struct{ l *slog.Logger }
//
// func WithLogger(l *slog.Logger) Option {
//   return &loggerOption{l}
// }
//
// func (o *loggerOption) apply(co *clientOptions) {
//   co.logger = o.l
// }
// ----
// --
//
// [.notes]
// --
// Doing so allows you to provide
// a readable string representation of the options (*step*),
// if you want.
//
// // TODO: move to next to diagram?
//
// Interface or not, the pattern is quite flexible:
//
// * You can add an option that takes a pointer to something
//   and fills that with a result when the operation finishes.
//   This is how you can produce new outputs from functions
//   that use functional options.
// * You can provide options that are composed of other options,
//   or transform, scope, or unset other options.
// * You can even decide that options are fallible,
//   and have the option type return an error,
//   which you then inspect in the function that consumes it.
//
// All in all, this is a pretty powerful tool.
// --
//
// [.columns.wrap]
// == Using functional options
//
// [.column.is-half.medium]
// --
// Don't use by default
//
// * High boilerplate
// * Harder to test
// * Corner cases
// --
//
// [.column.is-half.medium]
// --
// Good for
//
// * Several options
// * Few required parameters
// * Composability
// --
//
// [.column.is-full%step]
// Prefer parameter objects
//
// [.notes]
// --
// Some tips on using functional options:
//
// * First, don't use by default.
//   That is, don't reach for this tool first.
//   Functional options are great when they fit, but otherwise:
// ** The cost in boilerplate is very high
// ** For consumers, they make testing difficult
// ** There are corner cases in how options combine
//    that are usually not a problem:
// *** What happens if loggers are provided twice?
//     Do you overwrite or merge?
// *** If you merge, how do you unset an option that a caller has supplied?
// ** Remember, these are just opaque interfaces or function references.
//    They aren't comparable or introspectable.
//    Harder to test, harder to inspect and modify.
// * Functional options are usually a good fit for functions where:
// ** you have a *bunch* of options -- and these must be optional.
//    No required options --
// ** and you have very few required parameters.
// ** If the operations that the options perform are composable,
//    functional options are probably a good fit.
//
// Basically, (*step*) prefer parameter objects by default
// --
