[%auto-animate]
= Accept ``interface``s

Dependencies should be interfaces +
*not* concrete implementations

[.noborder, cols=">.^1,<.^2a",frame=none]
|====

| ðŸ™
| [source,go]
----
func Parse(f *os.File) (Node, error)
----

| ðŸ™‚
| [source%linenums,go]
----
func Parse(r io.Reader) (Node, error)
----

|====

[.notes]
--
When you're accepting an abstraction as input,
it should be an interface, not a concrete implementation.
Otherwise you're left with no room for expansion.

This is generally a good choice if two components
are very loosely coupled.
For example, my parser doesn't *have* to know that it's reading from a file.

This doesn't apply only to interfaces that already exist.
--

[%auto-animate]
= Accept ``interface``s

[.noborder, cols=">.^1,<.^2a",frame=none]
|====

| ðŸ™
| [source,go]
----
func Login(c *http.Client) (Token, error)
----

| ðŸ™‚
| [source%linenums,go]
----
type HTTPClient interface {
  Do(*http.Request) (*http.Response, error)
}

func Login(c HTTPClient) (Token, error)
----

|====

[.notes]
--
You can define and accept interfaces even for types you don't own
with only those methods that you need.

Doing this allows you to extend your input with upcasting.
--

[%auto-animate%auto-animate-restart.columns]
= Accept ``interface``s

[.column.medium]
--
Extend by upcasting interfaces
--


[column]
--
[source%linenums,go,data-id=Parse]
----
func Parse(r io.Reader) (Node, error) {
  /* ... */
}
----
--

[.notes]
--
For example, if my old Parse function
wanted to know the file name to use in error messages,
if I was using `*os.File`, I could just call `File.Name`.

But with the interface, I have to upcast it like so...
--

[%auto-animate.columns]
= Accept ``interface``s

[.column]
--
Extend by upcasting interfaces

[%step.medium.text-left]
====
Breaks if wrapped
[source,go]
----
type countLines struct{ io.Reader }
Parse(&countLines{file}) // oops!
----
====

[%step.medium]
* Make it obvious
* Use small interfaces
--

[column]
--
[source%linenums,go,data-id=Parse,highlight="1,3-5"]
----
func Parse(r io.Reader) (Node, error) {
  name := "<unknown>"
  if src, ok := r.(Source); ok {
    name = src.Name()
  }
  /* ... */
}
----

[source%linenums,go,data-id=Source]
----
type Source interface {
  io.Reader
  Name() string
}
----
--

[.notes]
--
I define a new interface named `Source`.
Its `Name()` method matches `os.File.Name()`.

So if the `io.Reader` passed into `Parse` implements this method,
I'll use the file name.
Otherwise, I'll fall back to unknown.

This method is great;
it allows me to *optionally* upgrade an abstraction I'm consuming
and make it richer.

However, it's not magic. It's easily breakable. (*step*)
If a user wraps the interface in an object
that doesn't know to implement the optional functionality,
that upgrade path is lost.

To help mitigate that:

* (*step*)
  Make the upgrade path obvious with documentation and convention.
  Make it so that a caller loses the upgrade path only if they intended to.
*  (*step*) And prefer to use smaller interfaces.
  It's easier to talk about the upgrade path
  when there's only one method to talk about.
--

// [.columns.wrap]
// == Using upcast
//
// [.column.is-full.highlight-red%step]
// Breaks if wrapped
//
// [.column.is-half]
// Make it obvious
//
// [.column.is-half]
// Use small interfaces
//
// [.notes]
// --
// This is a pretty powerful tool;
// with it, a function can provide optional upgrade paths on any input interface.
// It can support optional hooks into the business logic
// without polluting the core interface.
//
// However, it's not magic. It's easily breakable. (*step*)
//
// If the concrete type that implements the optional interface,
// is accidentally wrapped in another object (like a middleware)
// that does not implement that optional functionality,
// then we can't do anything about it.
// That upgrade path is lost.
//
// To help mitigate that, if you use this tool:
//
// * First, make the presence of the upgrade path obvious
//   with documentation and convention.
//   When a caller loses the upgrade path with wrapping,
//   it should always be intentional.
// * Second, use small interfaces.
//   It's easier to talk about the upgrade path
//   when the upgrade path interface has only one method.
// --
