:fix-conds: 🔭 Large scoped conditions

= {fix-conds}

*Remove* special cases based on conditions +
that *don't change* in the *current context*

[%step]
[pikchr, height=400px]
....
X: [
A: arrow <-> right 2in

dot at (A.wid * 0.25, 0)

line from (A.wid * 0.5, 0.1in) down 0.2in
text "Current" with .s at last.n

dot at (A.wid * 0.75, 0)
arrow dashed rad 0.1in down 0.2in then left until even with 1st dot then up to 1st dot
line invis "if true" mono below from 0.2in south of 1st dot right until even with last dot
]


Y: [
A: arrow <-> right 2in

dot at (A.wid * 0.25, 0)

line from (A.wid * 0.75, 0.1in) down 0.2in
text "Current" with .s at last.n

dot at (A.wid * 0.5, 0)
arrow dashed rad 0.1in down 0.2in then left until even with 1st dot then up to 1st dot
line invis "if true" mono below from 0.2in south of 1st dot right until even with last dot
] with n at 1in south of last

arrow color gray from 0.3in south of X.s to Y.n
....

[.notes]
--
One great place to find the abstraction is by trying to eliminate
large scoped conditions.

What I mean by that is special cases -- conditions and if statements --
based on variables that have a larger scope than the current context.

The intuition behind this idea is this:
(*step*)
If the condition is based on a value that doesn't change in the current scope,
then the condition will also not change.
Therefore, we should remove it from the current scope,
and evaluate it somewhere where it might.

This might be better demonstrated with an example...
--

[%auto-animate.columns]
== {fix-conds}

[.column.is-one-third]
--
[source%linenums,go,data-id=left]
----
type SiteGen struct {
  /* ... */
  LinkStyle LinkStyle
}
----

[source.medium,go]
----
type LinkStyle int

const (
  LinkStyleDir   LinkStyle = iota
  LinkStylePlain
  LinkStyleHTML
)
----
--

[.column.is-two-thirds%step]
[source%linenums,go,data-id=right]
----
func (g *SiteGen) RelativeURL(dst *Page) string {
  /* ... */
  switch g.LinkStyle {
  case LinkStyleDir:
    return u + "/"
  case LinkStylePlain:
    return strings.TrimSuffix(u, "/")
  case LinkStyleHTML:
    return u + ".html"
  }
}
----

[.notes]
--
Think back to the static website example.

We placed LinkStyle enum into the SiteGen struct.
If we left it at that, (*step*) SiteGen probably consumed it like this.
An if-else or a switch statement rendering the link based on the style.

This right here is a good place to find the abstraction.
The outcome of that switch statement will never change
for a single SiteGen instance.

We should make this decision in an outer context,
and pass in something that SiteGen can use unconditionally.

For example...
--

[%auto-animate.columns.wrap]
== {fix-conds}

[.column.is-one-third]
--
[source%linenums,go,data-id=left, highlight="1-|3"]
----
type SiteGen struct {
  /* ... */
  LinkStyler LinkStyler
}
----
--

[.column.is-two-thirds]
--
[source,go, highlight="1-|3"]
----
func (g *SiteGen) RelativeURL(dst *Page) string {
  /* ... */
  return g.LinkStyler.StyleLink(u)
}
----
--

[.column.is-one-third]
--
[source,go]
----
type LinkStyler interface {
  StyleLink(string) string
}

type (
  DirLinkStyler   /* ... */
  PlainLinkStyler /* ... */
  HTMLLinkStyler  /* ... */
)
----
--

[.column.is-two-thirds]
--
[source%linenums,go,data-id=right]
----
func (DirLinkStyler) StyleLink(u string) string {
    return u + "/"
}

func (PlainLinkStyler) StyleLink(u string) string {
    return strings.TrimSuffix(u, "/")
}

func (HTMLLinkStyler) StyleLink(u string) string {
    return u + ".html"
}
----
--

[.notes]
--
This might seem similar to an example we saw earlier:

* (*step*) We've switched a LinkStyler interface
* (*step*) RelativeURL no longer evaluates the condition.
* Something in the outer scope already decided for it,
  and passed in the right LinkStyler implementation
  for it to use unconditionally.

This idea of removing conditions with larger scope
applies in other contexts too.

For example, instead of writing `if production { .. }` in 5 different places,
decide whether you're in production well in advance,
and inject an object that behaves as one should in production or development --
as the case may be.
--
