[%auto-animate.columns]
= String typing

[.column]
--
[.medium]
Over-reliance on strings

[source%linenums,go,data-id=isHTTP]
----
func isHTTP(addr string) bool {
  return strings.HasPrefix(addr, "http://") ||
    strings.HasPrefix(addr, "https://")
}
----
--

[.column]
--
[source%linenums,go,data-id=download]
----
func download(addr string) {
  if isHTTP(addr) {
    http.Get(addr)
  } else {
    log.Panic("unsupported:", addr)
  }
  /* ... */
}
----
--

[.notes]
--
String typing. This is when you use strings everywhere.

Here's a hypothetical snippet of code,
not at all inspired by actual production code:
a function that takes a string, and if it's an HTTP URL, downloads it.

Forgive the error handling in this example,
but other than that, this is pretty simple.

I would say this is already problematic because
we're interpreting the structure inside 'addr' twice.
But let me make it messier. Suppose we also add SSH support.
--

[%auto-animate.columns]
== String typing

// NOTE: If this example changes significantly, concept-flow must too.

[.column]
--
Over-reliance on strings

[source%linenums,go,data-id=isHTTP]
----
func isHTTP(addr string) bool {
  return strings.HasPrefix(addr, "http://") ||
    strings.HasPrefix(addr, "https://")
}
----

[source%linenums,go,data-id=ssh]
----
func isSSH(addr string) bool {
  return strings.HasPrefix(addr, "ssh://")
}

func sshDownload(addr string) {
  addr = strings.TrimPrefix(addr, "ssh://")
  /* ... */
}
----
--

[.column]
--
[source%linenums,go,data-id=download]
----
func download(addr string) {
  if isHTTP(addr) {
    http.Get(addr)
  } else if isSSH(addr) {
    sshDownload(addr)
  } else {
    log.Panic("unsupported:", addr)
  }
  /* ... */
}
----
--

[.notes]
--
Now I'm interpreting the structure inside addr a bunch of times:

* once each in isSSH and sshDownload
* twice in isHTTP
* once again down the line in http.Get

This is easily breakable. There's a better way.
--

[.columns.wrap]
== String typing

:url-parse-early: https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/

[.column.is-half]
--
> Parse, don't validate

[.small.text-right]
-- link:{url-parse-early}[Alexis King]

[.medium]
* Turn `string` into `struct`
* `struct` value is evidence of validity
* [.step, step=2]#Eliminate chaos early#
--

[.column.is-half]
--
[step=1]
[pikchr]
....
down
L1: line dotted go down 0.5in
box "Parse" mono fit rad 0.05in
line same

text "Chaos" big with e at 0.2in w of L1.n+(0, -0.1in)
text "Order" big with w at 0.2in e of L1.n+(0, -0.1in)

text "\"https://example.com/magic.zip\"" at 0.25in south of Chaos+(-0.5in,0)
arrow chop thin rad 0.1in from last down until even with Parse then to Parse

move to 0.7in east of Parse+(0, -0.2in)
down
HTTPS: box "https" fit
box "example.com" fit with nw at last.sw
box "magic.zip" fit with nw at last.sw

arrow chop thin rad 0.1in from Parse go right until even with HTTPS then to HTTPS
....
--

[.notes]
--
You may have already heard this, or a variant of this before:
Parse, don't validate.

The idea, simplified, is this:
when you check if a string is valid,
don't leave it a string afterwards.
Turn it into a different structure
that represents the validity of the string.
If you have an object of that type,
you can assume it came from a valid string.

I like to visualize it like this (*step*):

* There is chaotic data on the left.
  It's annoying to deal with and I don't want it.
* If it successfully passes through Parse,
  It becomes ordered data -- easy to operate on.
* (*step*) Aim to convert chaos to order
  as soon as it enters your program

Going back to the example:
--

[%auto-animate.columns]
== String typing

[.column]
--
Over-reliance on strings

[source%linenums,go,data-id=isHTTP]
----
func isHTTP(addr string) bool {
  return strings.HasPrefix(addr, "http://") ||
    strings.HasPrefix(addr, "https://")
}
----

[source%linenums,go,data-id=ssh]
----
func isSSH(addr string) bool {
  return strings.HasPrefix(addr, "ssh://")
}

func sshDownload(addr string) {
  addr = strings.TrimPrefix(addr, "ssh://")
  /* ... */
}
----
--

[.column]
--
[source%linenums,go,data-id=download]
----
func download(addr string) {
  if isHTTP(addr) {
    http.Get(addr)
  } else if isSSH(addr) {
    sshDownload(addr)
  } else {
    log.Panic("unsupported:", addr)
  }
  /* ... */
}
----
--

[.notes]
--
I should forget that `addr` is a string as early as I can.
In this case, I can use `net/url.Parse` to do that.
--

[%auto-animate.columns]
== String typing

[.column]
--
Chaos to order

[source%linenums,go,data-id=isHTTP,highlight="1"]
----
func isHTTP(addr *url.URL) bool {
  return addr.Scheme == "http" ||
    addr.Scheme == "https"
}
----

[source%linenums,go,data-id=ssh,highlight="1,5"]
----
func isSSH(addr *url.URL) bool {
  return addr.Scheme == "ssh"
}

func sshDownload(addr *url.URL) {
  /* ... */
}
----
--

[.column]
--
[source%linenums,go,data-id=download, highlight="1-2,6,8-9"]
----
func download(addrs string) {
  addr, err := url.Parse(addrs)
  if err != nil {
    log.Panic(err)
  }
  if isHTTP(addr) {
    http.Get(addrs)
  } else if isSSH(addr) {
    sshDownload(addr)
  } else {
    log.Panic("unsupported:", addr)
  }
  /* ... */
}
----
--

[.notes]
--
I convert the string to a URL at the entry point,
and then the same parsed representation is inspected
instead of dealing with chaotic data repeatedly.

In this example, `url.Parse` already existed,
but the point I'm making here doesn't hold just for that --
or for just strings for that matter.
--

// [%auto-animate.columns]
// == String typing
//
// [.column]
// --
// [source%linenums.medium,go,data-id=helpers]
// ----
// func httpGet(addr *url.URL) {
//   /* ... */
// }
//
// func sshDownload(addr *url.URL) {
//   /* ... */
// }
// ----
// --
//
// [.column]
// --
// [source%linenums.medium,go,data-id=do]
// ----
// func download(addrs string) {
//   addr, err := url.Parse(addrs)
//   if err != nil {
//     log.Panic(err)
//   }
//   switch addr.Scheme {
//   case "http", "https":
//     httpGet(addr)
//   case "ssh":
//     sshDownload(addr)
//   default:
//     log.Panic("unsupported:", addr)
//   }
//   /* ... */
// }
// ----
// --
//
// [.notes]
// --
// Ah, that's better.
//
// In this example, `url.Parse` already existed,
// but the point I'm making here doesn't hold just for that.
// --

[.columns.wrap]
== String typing

[.column.is-one-third.medium.text-right]
Chaos

[.column.is-two-thirds.medium.text-left]
| Order

[.column.is-one-third.medium]
--
[source, go]
----
strings.HasPrefix(addr, "ssh://")
----
--

[.column.is-two-thirds]
--
[source, go]
----
u, err := url.Parse(addr)
----
--

[.column.is-one-third]
--
[source, go]
----
var uuid string
----
--

[.column.is-two-thirds]
--
[source, go]
----
type UUID [16]byte
func ParseUUID(string) (UUID, error)
----
--

[.column.is-one-third]
--
[source, go]
----
var ts int64
----
--

[.column.is-two-thirds]
--
[source, go]
----
t := time.UnixMilli(ts)
----
--

[.column.is-one-third]
--
[source, go]
----
strings.Replace(s, "%VAR%", val)
----
--

[.column.is-one-third.medium]
--
[source, go]
----
type Node struct{ Var, Str string }
type Template []Node
func Parse(string) Template
----
--

[.column.is-one-third.medium]
--
[source, go]
----
tmpl := Parse(s)
tmpl.Render(
  map[string]string{"VAR": val},
)
----
--


[.notes]
--
Anytime you're dealing with chaotic data as input,
it's a good idea to convert it to order *once* at the entry point
and never touch it again.

* Matching on URLs? Parse it.
* Storing UUIDs? Parse it into the 128-bit number it is.
* Comparing timestamps? Is that milliseconds or seconds?
  At some point, two pieces of code will have
  different answers to that question and everything will break.
  Convert it to a `time.Time` at the entry point.
* Even for home-grown, string-replacement based templating,
  if it leaks outside, it can be worth it to parse it into a structure early
  and operate on that.

Untyped strings are chaos.
Turn the chaos to order as early as possible.
--
