[.columns%auto-animate%auto-animate-restart]
= {fix-bool}

[.column.medium]
--
[data-id=subtitle]
Overly specific booleans
--

[.column]
[source%linenums%step,go]
----
type SiteGen struct {
  /* ... */
}

func (g *SiteGen) RelativeURL(dst *Page) string {
  u := /* ... */
  return u + "/"
}

g.RelativeURL(p) // "path/to/dst/"
----

[.notes]
--
In similar vein to string typing is overly specific booleans.
This is pretty common.

Something exists and it works fine.
Someone wants a pretty specific customization.
To keep the fingerprint of this request small,
you add a boolean flag for that specific request.

Let me demonstrate. (*step*)

Suppose I have a static website generator.
It uses relative URLs to reference other pages.
These URLs always end with a trailing slash.

However, a user complains that their static website host
does not like these trailing slashes and they'd like to opt-out.
--

[.columns.wrap%auto-animate]
== {fix-bool}

[.column.is-full]
--
[data-id=subtitle]
Overly specific booleans
--

[.column%step]
--
[source,go]
----
func (...) RelativeURL(
  dst *Page,
  slash bool,
) string
----

[%hardbreaks]
Disruptive
Poorly scoped
--

[.column%step]
--
[source,go]
----
type SiteGen struct {
  /* ... */
  AddSlash bool
}
----

Disruptive
--

[.column%step]
--
[source,go]
----
type SiteGen struct {
  /* ... */
  OmitSlash bool
}
----

[.step.strike, step=4]#Good# +
[.step, step=4]#Not terrible#
--

[.notes]
--
Let's consider some options for the opt-out.

* (*step*) Add a `slash` parameter to RelativeURL.
** This will disrupt all calls to `RelativeURL` across the code base.
   That already makes it a non-starter.
** On top of that, it's also poorly scoped:
*** Even without looking at its implementation,
    we can guess that `SiteGen` is used once per website.
    On the other hand, `RelativeURL` will be used many times per website.
*** The `slash` parameter will not change between these calls because
    whether relative URLs should use slashes
    is not something that changes for each URL;
    you decide it once when you're generating the site.
    It's site-scoped, not URL scoped.
* (*step*) Okay, we could move it into a `SiteGen` level boolean.
** That's still not good enough.
   It's disruptive because the zero value -- the default value --
   of this new optional field is to *not* add the slashes,
   which changes behavior for all existing uses of `SiteGen`.
* (*step*) Fine, let's flip it. An `OmitSlash` field.
** That's good, (*step*) riiiight?
** (*step*) It's... Not great. Not terrible.
** One of its problems is that it's rigid and limiting.
   By being so specific, it limits what we can do in the future.
   What if we want to support adding `.html` as an option?
   Would that be another boolean? `AddHTML`?
   What happens when both booleans are set?

To figure out a better option,
we have to stop thinking of this feature in isolation.
The behavior has to be considered as part of the bigger SiteGen abstraction.

How about, instead of a binary choice of "add a slash or not,"
we think about it as "this is how links SiteGen should render links."

Perhaps "which of these N methods of rendering links should I use?"
And there's a standard tool for picking one of N...
--

[%auto-animate%auto-animate-restart.columns]
== {fix-bool}

[.column]
--
Use an enum

[source%linenums,go,data-id=LinkStyle,highlight="1-|1|4"]
----
type LinkStyle int

const (
  LinkStyleDir   LinkStyle = iota
  LinkStylePlain
)
----
--

[.column]
--
[source%linenums,go,data-id=SiteGen,highlight="1-|3"]
----
type SiteGen struct {
  /* ... */
  LinkStyle LinkStyle
}
----
--

[.notes]
--
Enums.

With enums, I'm able to

* (*step*) Define the concept of a link style
  that represents how links should be rendered.
* (*step*) Note that the zero value of link style is directory --
  the original behavior -- so that this change isn't disruptive
* I can then incorporate this (*step*) into my site generator
  as a site-level option

Modeling the concept allows us to introduce new link styles.
--

[%auto-animate.columns]
== {fix-bool}

[.column]
--
Use an enum

[source%linenums,go,data-id=LinkStyle]
----
type LinkStyle int

const (
  LinkStyleDir   LinkStyle = iota
  LinkStylePlain
  LinkStyleHTML
)
----
--

[.column]
--
[source%linenums,go,data-id=SiteGen]
----
type SiteGen struct {
  /* ... */
  LinkStyle LinkStyle
}
----
--

[.notes]
--
One with a trailing ".html", for example.
--
