= Exposed wire form

[pikchr%step, width=75%]
....
boxwid = 0.5in
ovalwid = 0.5in
linewid = 0.5in
lineht = 0.3in

Bad: [
right
text "Bad"; move 0.1in
text "..."
line 0.2in
box "Item"
arrow
oval "Submit"
arrow
cylinder wid boxwid
]
....

[pikchr%step, width=75%]
....
boxwid = 0.5in
ovalwid = 0.5in
linewid = 0.5in
lineht = 0.3in

Good: [
right
text "Good"; move 0.1in
text "..."
line 0.2in
box "Item"
arrow
oval "Submit"
down
arrow
box "DBItem"
right
arrow
cylinder wid boxwid

line dashed from (Item.w.x, (Item.s.y+DBItem.n.y)/2) right until even with last.e
]
....

[.notes]
--
I just talked about how maps at boundaries can leak complexity.
This is based on the same principle.

(*step*) If the input or output of a package is a data type
that is also serialized or deserialized
and crosses system boundaries --
that is, it gets sent over the wire or stored in a database --
that's very likely a leak.

Ideally, (*step*) you want an intermediate data type
that is coupled to what gets serialized,
and an explicit step converting the external type
to this wire-level form.

This effectively draws a boundary between the business logic
and the database or wire representation.
--
