[.columns]
= {fix-big-iface}

[.column]
--
Big interfaces cause +
a tight coupling +
between abstractions
--

[.column.is-two-thirds%step]
--
> The bigger the interface, +
> the weaker the abstraction.
>
> -- Rob Pike, https://www.youtube.com/watch?v=PAAkCSZUG1c&t=5m17s&themeRefresh=1[Gopherfest 2015]
--

[.notes]
--
Another way to misuse interfaces for abstractions
is by defining a really big interface.

Big interfaces indicate a tight coupling
between the producer of the abstraction and the consumer.
Or as Rob Pike put it, (*step*)
the bigger the interface, the weaker the abstraction.

I want to share a couple tips to help you achieve smaller interfaces.
--

== {fix-big-iface}

Making interfaces smaller

* Follow the request path
* Use functions
* Build a strong core

[.notes]
--
* First: Follow the request path.
  Think about methods of the interface
  that are going to be called multiple times
  versus once.
* Second: use functions.
  You'll find that some of the functionality of the interface,
  could be implemented as a function.
* Third: Wrap the interface in a richer struct.

This is all better demonstrated through examples,
so let me run through one:
--

[.columns]
== Follow the request path

[.column]
--
[.medium]
Add methods from +
the request path

[source%step,go]
----
type Store interface {
  Get(string) (string, error)
  Set(k, v string) error
}
----

[%step.medium]
No `Close()`

[source%step,go]
----
s := NewRedisStore(addr)
defer s.Close()
run(s)
// Given,
//   func run(Store)
----
--

[.column]
--
[source,go]
----
type RedisStore struct{ /* ... */ }

func NewRedisStore(addr string) *RedisStore

func (*RedisStore) Get(string) (string, error)

func (*RedisStore) Set(k, v string) error

func (*RedisStore) Close()
----
--

[.notes]
--
Follow the request path.

When deciding what goes on the interface,
don't just list all the methods of the object on the interface.
Think about the request path:
methods of the object that consumers will want to call --
probably many times.

For example, suppose we have this key-value store backed by Redis.
It has Get and Set methods as you might expect,
and a Close method to close the store and clean up resources.

What should go in the interface?
Follow the request path says:

 * (*step*) only Get and Set
 * (*step*) no Close

Why?

* Close is not part of the request path --
  it won't be called many times.
  It will be called exactly once (*step*)
  probably in main, when we set up the Redis store.
* Plus if you think about it, not every Store will have a Close method.
  An in-memory data store probably won't.

So we leave Close out of the interface.
--

[.columns.wrap]
== Use functions

[.column.is-full.medium%step]
Convenience methods stay out of the interface

[.column.is-two-thirds]
[source%linenums,go,data-id=SetMany,highlight="1-|3"]
----
func (s *RedisStore) SetMany(ks, vs []string) error {
  for i, k := range ks {
    err := s.Set(k, vs[i])
    if err != nil {
      return nil, err
    }
  }
  return nil
}
----

[.notes]
--
Okay, but what about convenience methods?
Suppose the RedisStore also has a `SetMany` method.
That's on the request path.
Should it go on the interface?

Note that the implementation of SetMany
isn't doing anything special.
It just calls `Set`.

So, (*step*) (*step*) don't put it on the interface.
Instead, turn it into a function that operates on any Store.
--

[%auto-animate.columns.wrap]
== Use functions

[.column.is-full.medium]
Convenience methods stay out of the interface

[.column.is-half]
[source%linenums,go,data-id=SetMany, highlight="1,3"]
----
func SetMany(s Store, ks, vs []string) error {
  for i, k := range ks {
    err := s.Set(k, vs[i])
    if err != nil {
      return nil, err
    }
  }
  return nil
}
----

[.column.is-half]
--
[source%step, go, data-id=RedisSetMany]
----
func (s *RedisStore) SetMany(
  ks, vs []string,
) error {
  return s.redisc.superFastSetMany(ks, vs)
}
----
--

[.notes]
--
(Wait a second to make the change obvious.)

Of course, this isn't completely realistic.
The RedisStore probably had a more optimal way
of setting many items (*step*) using Redis-specific functionality.

That's not a problem;
we can support an optional upgrade path for SetMany with upcasting.
--

[%auto-animate.columns.wrap]
== Use functions

[.column.is-full.medium]
Convenience methods stay out of the interface

[.column.is-half]
--
[source%linenums,go,data-id=SetMany,highlight="2,3,6"]
----
func SetMany(s Store, ks, vs []string) error {
  if sm, ok := s.(SetManyStore); ok {
    return sm.SetMany(ks, vs)
  }
  for i, k := range ks {
    err := s.Set(k, vs[i])
    if err != nil {
      return nil, err
    }
  }
  return nil
}
----
--

[.column.is-half]
--
[source%linenums,go,data-id=SetManyStore]
----
type SetManyStore interface {
  Store
  SetMany(ks, vs []string) error
}
----

[source, go, data-id=RedisSetMany]
----
func (s *RedisStore) SetMany(
  ks, vs []string,
) error {
  return s.redisc.superFastSetMany(ks, vs)
}
----
--

[.column.is-full.medium]
Upcast to upgrade

[.notes]
--
Here, we've defined a new interface SetManyStore,
that RedisStore happens to implement.

The SetMany function will attempt to use the optimal version
if available, falling back to a for loop if not.
--

[.columns.wrap]
== Build a strong core

[.column.is-full.medium]
Wrap a small interface with powerful functionality

[.column.is-half]
--
[source%linenums%step,go,data-id=DataStore, step=2]
----
type DataStore struct{ s Store }

func (*DataStore) Get(string) (string, error)
func (*DataStore) Set(k, v string) error
----
--

[.column.is-half]
--
[source%step,go, step=1]
----
type Store interface {
  Get(string) (string, error)
  Set(k, v string) error
}
----
--

[.column]
--
[source%step%linenums,go,data-id=SetMany, step=3]
----
func (d *DataStore) SetMany(ks, vs []string) error {
  if sm, ok := s.(SetManyStore); ok {
    return sm.SetMany(ks, vs)
  }
  /* ... */
}
----
--

[.column]
--
[source%linenums,go,data-id=SetManyStore, step=3]
----
type SetManyStore interface {
  Store
  SetMany(ks, vs []string) error
}
----
--

[.notes]
--
Lastly, build a strong core.
What I mean by that is --
start with a small, minimal interface, wrap it in a struct,
and build more convenience, more powerful functionality around it.

For example,

* (*step*) Let's go back to the `Store` interface.
* (*step*) We'll introduce a struct, `DataStore` that wraps it.
  The struct implements Get and Set, so it's a valid Store as well.
* (*step*) Then we can add a `SetMany` method to `DataStore`.
  The SetMany method can use the same upgrade path
  that we used for the SetMany function in the last example.

It gives us the best of all worlds:

* Small, loosely coupled, interface
* The ability to add new convenient methods as we see fit
  with optional upgrade paths for implementations that want them
--
