[%auto-animate.columns.wrap]
= {fix-premature-iface}

[.column.is-half]
--
[%step.medium]
* *Unnecessary* +
  Interfaces match dynamically
* *Inflexible* +
  New methods are disruptive
* *Complex* +
  Constructor is required
--

[.column.is-half]
[source%linenums, go, data-id=impl]
----
type Client interface {
  List() ([]*Post, error)
}

func New() Client {
  return &impl{/* ... */}
}

type impl struct{/* ... */}

func (*impl) List() ([]*Post, error) {
  /* ... */
}
----

[.notes]
--
Premature interfaces.

This is a pretty common thing.
We're defining an abstraction,
so we define it as an interface,
and keep the implementation private.

I want to advise against this as your default choice
because

. (*step*) It's unnecessary.
  Go matches interfaces dynamically,
  so a type doesn't need to declare interfaces it implements
  at declaration time.
. (*step*) It introduces inflexibility.
  We cannot expand the interface easily.
  Adding new methods to this interface is a disruptive change
  because it'll break other implementations.
.. And if that's not a concern because there aren't other implementations,
   then we go back to: it's unnecessary.
. (*step*) It comes with a minimum required complexity.
  You *have* to define a constructor;
  there's no way to use the zero value or plain object directly.

Looking back to the expansion section, the fix is to...
--

[%auto-animate.columns.wrap]
== {fix-premature-iface}

[.column.is-half]
--
Use a struct

[.medium%step]
* Producers expose concrete types
* Consumers define interfaces

[source%step,go]
----
type PostClient interface {
  List() ([]*Post, error)
}

func NewHandler(pc PostClient) *Handler {
  /* ... */
}
----
--

[.column.is-half]
[source%linenums, go, data-id=impl]
----
type Client struct{/* ... */}

func New() *Client {
  return &Client{/* ... */}
}

func (*Client) List() ([]*Post, error) {
  /* ... */
}
----

[.notes]
--
Use a struct instead.

Or more generally, as a default:

* (*step*) Producers of abstractions export concrete types.
  If they have a constructor, they return the concrete type from it.
* (*step*) Consumers of abstractions can define interfaces as needed.
  For example... (*step*).

I want to clarify that this isn't a rule, but more like a guideline.
Change your default choice to this,
and it'll be the right choice most of the times.
--

== {fix-premature-iface}

Producers may define interfaces for...

* Single operation interfaces
* Multiple implementations
* Wrapped abstractions
* Others

[.notes]
--
Of course, there are cases where producers of abstractions
*should* define their interfaces.

Here's a non-exhaustive list of some of them:

* Interfaces that represent a single operation --
  basically just a step above a function reference.
  Think back to the callbacks vs interfaces part of this talk.
* Or, the package defines multiple implementations of the interface,
  and it's common for consumers to be polymorphic over these implementations.
* Consumers regularly wrap the abstraction you before using it or passing it on.
  Think middleware.

Again, I'm sure there are others;
I don't have the time to make this comprehensive.

The point I'm making is that by default,
producers of abstractions should not declare the interface for them.
--
