= Global state

[.notes]
--
Let's talk about global state.

Okay, yeah, you all probably already know global variables should be avoided.
That's not what I want to talk about.
I want to talk about...
--

:process-globals: 🍝 Implicit process globals

[.columns.wrap]
== {process-globals}

[%step.column.is-half]
--
[.medium.text-left]
Process globals include

[source,go]
----
os.Stdout
os.Stdin
os.Stderr
os.Getenv(k)
os.Setenv(k, v)
----
--

[.column.is-half]
--
[source%step,go]
----
if os.Getenv("FEATURE_MAGIC") != "" {
  fmt.Println("You're a wizard")
  return doMagic()
}
return beBoring()
----
--

[.column.medium.is-full]
--
[%step]
* Don't touch process globals outside `main`
* Isolate business logic from process state
--

[.notes]
--
Implicit process globals.

I'm referring to (*step*) standard out, standard in,
environment variables, etc.
These are all a form of global state for your program.

It's easy to use these anywhere in your program.
(*step*)
If environment variable is set, use cool new feature.
Log a message to standard out.

There's nothing wrong about this in particular.
However, I'd like to make the claim that (*step*)
you should not read or write process globals
outside the `main` package.

(*step*) Instead, isolate your business logic
from knowledge of the process state.
No package besides `main` should know about the process state.
--

== {process-globals}

[.medium]
Extract and inject process globals early in `main`

[cols="1a,1a,1a", frame=none]
|====

| [source,go]
----
os.Getenv("FEATURE_MAGIC")
----
2+| [source%step,go, step=1]
----
func main() {
  feats := Features{Magic: os.Getenv("FEATURE_MAGIC")}
  run(feats)
}
----

| [source,go]
----
fmt.Println(
  "You're a wizard",
)
----
| [source%step,go, step=2]
----
func main() {
  run(os.Stdout)
}
----
| [source%step,go, step=2]
----
func run(stdout io.Writer)
----

| [source,go]
----
os.Getenv
----
| [source%step,go, step=3]
----
func main() {
  run(os.Getenv)
}
----
| [source%step,go, step=3]
----
func run(
  getenv func(string) string,
)
----

|====

[.notes]
--
A good way to do this is to extract information from your process globals
as early as possible,
and then inject it down where it's needed.

* Need to check for a feature flag? (*step*)
  Extract all feature flags into a struct and pass that down.
* Need to write messages to the user? (*step*)
  Grab a reference to `os.Stdout`, and pass that down as an io.Writer.
* Need to look up arbitrary environment variables?
  That's okay; Go has function references.
  (*step*) Inject a reference to `os.Getenv` down where it's needed.

You're probably thinking that that `run` function
will get pretty ungainly if we do this for everything.

I agree. We can fix that.
--

[.columns.wrap]
== {process-globals}

[.column.is-full.medium]
Inject process globals

[.column.is-one-third]
--
[source,go]
----
type cliParams struct {
  Stdout io.Writer
  Stderr io.Writer
  Getenv func(string) string
}

func run(*cliParams)
----
--

[.column%step.is-two-thirds]
--
[source,go]
----
type App struct {
  Stdout io.Writer
  Stderr io.Writer
  Getenv func(string) string
}

func (*App) Run(args []string) (exitCode int)
----
--

[.notes]
--
We talked about parameter objects before.
That fits right in.

Or equivalently, (*step*) an object with a Run method.

Regardless, if you isolate your business logic from process globals,
you'll find that it makes your application logic much easier to test.
--
