= Tools

// TODO: picture of a toolbox
// TODO: Drop the do/don't for tools. Just show the tool.

[%step]
* Functions
* Abstractions

[.notes]
--
Well, before we start fixing things,
let's look inside our toolbox
for things that'll help us do it.

I'll talk about two kinds of tools (*step*):
tools for expanding functions, (*step*)
and tools for expanding abstractions.
--

= Tools for functions

[.notes]
--
Let's talk about functions first.
--

include::tool-params.adoc[]
include::tool-results.adoc[]
include::tool-func-opts.adoc[]

= Tools for abstractions

[.notes]
--
I just covered tools for expanding function inputs and outputs.

I'll cover abstractions now.
--

include::tool-accept-iface.adoc[]
include::tool-return-struct.adoc[]

= Tools for future-proofing

include::expansion-table.adoc[]

[.notes]
--
So to summarize, the starting toolbox contains:

* Parameters objects and result objects
  for expanding function inputs and outputs
* Functional objects for expanding both
* The practice of accepting interfaces,
  and the ability to upcast them,
  for expanding input abstractions
* And the practice of returning structs
  and adding methods to them,
  for expanding output abstractions
--

include::tool-initialize.adoc[]
