[.columns]
= Parameter objects

// TODO: less shit examples
// TODO: notes
// TODO: accept a struct and return a struct, and the signature will never break.

[.column.is-half]
--
[source,go]
----
func New(
  url string,
  token string,
  log *zap.Logger,
) *Client
----

[.text-left, step=1]
[.medium]#Use a parameter object# +
[.small]#for more than three parameters#
--

[%step.column.is-half, step=1]
--
[source,go]
----
type Config struct {
  URL   string
  Token string
  Log   *zap.Logger
}

func New(cfg *Config) *Client
----
--

// TODO: auto-animate

[.notes]
--
Parameter objects.
This is a fairly straightforward tool.

Put the parameters of your function in a struct.
This gives you the ability to add new *optional* parameters
without disrupting callers.

This is usually a good idea
once you cross the three parameter mark.
--

[.small]
== Adding new parameters

* Must be optional
* Use the zero value

[.notes]
--
Some quick tips for adding new parameters
to a parameter object:

* New parameters must be optional.
  Without this, all callers will break.
* For the new parameter, pick something with a zero value
  that matches the old behavior.
  That is, if the new parameter is at its zero value
  your code shouldn't do the thing that the new parameter allows.
** As an example, if you have something that TODO
   add `EnabledNewBehavior bool`, not `DisableNewBehavior bool`.
** On the other hand, if the behavior has already been active,
   and this is a means of opting out or changing it, TODO.
--
